site_name: Ruifeng's Notes - Machine Learning
site_url: https://huruifeng.github.io/ml_notes
site_author: Ruifeng Hu
site_description: >-
  Learn about Machine Learning.

repo_name: huruifeng/ml_notes
repo_url: https://github.com/huruifeng/ml_notes

copyright: Copyright &copy; 2024 Ruifeng Hu

theme:
  name: material
  custom_dir: docs/overrides

  palette: 
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  features:
    # - navigation.instant
    - navigation.indexes
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    # - navigation.sections  # expand all sections
    # - navigation.path
    # - navigation.prune
    - navigation.top

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/huruifeng
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ruifeng-hu-702b9383/
    - icon: fontawesome/solid/envelope
      link: mailto:huruifeng.cn@hotmail.com

extra_css:
  - assets/css/style.css

extra_javascript:
  - assets/js/myscript.js


plugins:
  - search
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          name: English
          build: true
          default: true  # Set English as the default language
          site_name: "Machine Learning Notes"
        - locale: zh
          name: 中文
          build: true  # Ensure this language is built properly
          site_name: "机器学习笔记"
          theme:
            palette:
              primary: red
          nav_translations:
            Home: 首页
            Getting Started: 入门指南
            Advanced: 高级主题


nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Advanced: advanced.md