site_name: Ruifeng's Notes - Machine Learning
site_url: https://huruifeng.github.io/ml_notes
site_author: Ruifeng Hu
site_description: >-
  Learn about Machine Learning.

repo_name: huruifeng/ml_notes
repo_url: https://github.com/huruifeng/ml_notes

copyright: Copyright &copy; 2024 Ruifeng Hu

theme:
  name: material
  custom_dir: overrides
  language: en  # Default UI language
  alternate: true  # Show language switcher
  palette: 
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    # - navigation.tabs
    # - navigation.sections  # expand all sections
    # - navigation.path
    # - navigation.prune
    - navigation.top

extra:
  alternate:
    - name: English
      link: en/
      lang: en
    - name: 中文
      link: zh/
      lang: zh
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/huruifeng
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ruifeng-hu-702b9383/
    - icon: fontawesome/solid/paper-plane
      link: mailto:huruifeng.cn@hotmail.com




extra_css:
  - assets/css/style.css

extra_javascript:
  - assets/js/myscript.js



# Page tree
nav:
  - Home: index.md
  - Getting started:
    - Installation: getting-started.md
    - Creating your site: creating-your-site.md
    - Publishing your site: publishing-your-site.md
    - Customization: customization.md
    - Conventions: conventions.md
    - Browser support: browser-support.md
    - Enterprise feedback: enterprise-support.md
    - Philosophy: philosophy.md
    - Alternatives: alternatives.md
    - License: license.md
    - Tutorials:
      - tutorials/index.md
      - "Blogs":
        - tutorials/blogs/basic.md
        - tutorials/blogs/navigation.md
        - tutorials/blogs/engage.md
      - "Social cards":
        - tutorials/social/basic.md
        - tutorials/social/custom.md
    - Changelog:
      - changelog/index.md
      - How to upgrade: upgrade.md
  - Setup:
    - setup/index.md
    - Changing the colors: setup/changing-the-colors.md
    - Changing the fonts: setup/changing-the-fonts.md
    - Changing the language: setup/changing-the-language.md
    - Changing the logo and icons: setup/changing-the-logo-and-icons.md
    - Ensuring data privacy: setup/ensuring-data-privacy.md
    - Setting up navigation: setup/setting-up-navigation.md
    - Setting up site search: setup/setting-up-site-search.md
    - Setting up site analytics: setup/setting-up-site-analytics.md
    - Setting up social cards: setup/setting-up-social-cards.md
    - Setting up a blog: setup/setting-up-a-blog.md
    - Setting up tags: setup/setting-up-tags.md
    - Setting up versioning: setup/setting-up-versioning.md
    - Setting up the header: setup/setting-up-the-header.md
    - Setting up the footer: setup/setting-up-the-footer.md
    - Adding a git repository: setup/adding-a-git-repository.md
    - Adding a comment system: setup/adding-a-comment-system.md
    - Building an optimized site: setup/building-an-optimized-site.md
    - Building for offline usage: setup/building-for-offline-usage.md
    - Extensions:
      - setup/extensions/index.md
      - Python Markdown: setup/extensions/python-markdown.md
      - Python Markdown Extensions: setup/extensions/python-markdown-extensions.md
  - Plugins:
    - plugins/index.md
    - Blog: plugins/blog.md
    - Group: plugins/group.md
    - Info: plugins/info.md
    - Meta: plugins/meta.md
    - Offline: plugins/offline.md
    - Optimize: plugins/optimize.md
    - Privacy: plugins/privacy.md
    - Projects: plugins/projects.md
    - Search: plugins/search.md
    - Social: plugins/social.md
    - Tags: plugins/tags.md
    - Typeset: plugins/typeset.md
    - Requirements:
      - Image processing: plugins/requirements/image-processing.md
      - Caching: plugins/requirements/caching.md
  - Blog:
    - blog/index.md